global using SimplifiedPicPay.Api.Extensions;
global using SimplifiedPicPay.Api.Common.Api;
global using SimplifiedPicPay.Api;
global using SimplifiedPicPay.Api.Common.ExceptionHandlers;
global using SimplifiedPicPay.Api.Common.Logic;
global using SimplifiedPicPay.Api.Common.Helpers;
global using SimplifiedPicPay.Api.Common.Handlers;
global using Scrutor;
global using SimplifiedPicPay.Api.Common.Entities;
